### ISSUE TITLE
Warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by julien51** [zpao/qrcode.react#134]
It appears that `QRCodeCanvas` uses a deprecated method.
 
```
    1: "Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.·
    * Move data fetching code or side effects to componentDidUpdate.
    * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
    * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.·
    Please update the following components: %s", "QRCodeCanvas"
```

Is this a known issue?

**Comment by helloitsm3** [comment]
Yes. I've created a pull request and hopefully he'll accept it.

**Comment by zpao** [comment]
FWIW, this is only a dev mode issue. As noted in the PR, will take a look soon and figure out how to go about versioning.

**Comment by antonenkokrg** [comment]
same problem

**Comment by mjbertenburg** [comment]
Same here, I would appreciate a fix any time soon. :)

**Comment by AndyRN** [comment]
This package is great, would love to see the deprecation warning resolved 👍

**Comment by trouba** [comment]
Hello, any news on this ?

**Comment by LukeHardyLexacom** [comment]
Any update on this please?

**Comment by helloitsm3** [comment]
@zpao

**Comment by xinaesthete** [comment]
This is pretty annoying noise during dev.

**Comment by trm217** [comment]
This is indeed very annoying. I would appreciate it, if this could be resolved. The PR has been open for 5 months.

**Comment by trouba** [comment]
@trm217 Took me 10mn to switch to this lib https://github.com/rosskhanas/react-qr-code#readme

**Comment by xinaesthete** [comment]
> @trm217 Took me 10mn to switch to this lib https://github.com/rosskhanas/react-qr-code#readme

I was actually using that and I think it took me less than 10 minutes to switch to this when for some reason it was giving me some trouble with my npm/vite configuration.

**Comment by boillatlucas** [comment]
Hello, any news on this ?

**Comment by jyboy** [comment]
Any updates?

**Comment by BlairSweigman** [comment]
Just tried it today on my 17.0.2, same error. I guess they gave up after version 1.0.1

**Comment by artola** [comment]
@zpao Any update on this? We have some PR already ongoing, can be merged? It is just a few lines if we are not be backward compatible, may be just publish a new version for such breaking change.

```js
static getDerivedStateFromProps(props, state) {
    const currentSrc = state.imageSrc;
    const nextSrc = props.imageSettings?.src;

    if (currentSrc !== nextSrc) {
      return {imgSrc: nextSrc, imgLoaded: false};
    }
  }
```

**Comment by AustinRhoads** [comment]
Any update????

**Comment by zpao** [comment]
There's no way to fix this and support the same version range (down to 15.x), so I'm not going to in this major version (1.x). In order to use the `unsafe_*` lifecycle methods, I'd have to bump that lowest support version to 16.3.

I have a rewrite pending which will have a lower bound of React 16.8 (using hooks), which you can track in #169.

**Comment by AustinRhoads** [comment]
Thanks!

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 23, 2022 at 1:54 PM, Paul ***@***.***> wrote:   


There's no way to fix this and support the same version range (down to 15.x), so I'm not going to in this major version (1.x). In order to use the unsafe_* lifecycle methods, I'd have to bump that lowest support version to 16.3.

I have a rewrite pending which will have a lower bound of React 16.8 (using hooks), which you can track in #169.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
