### ISSUE TITLE
Logos should keep the original aspect ratio and not squeeze

### ISSUE THREAD

**Issue by andyfitz** [zpao/qrcode.react#167]
This is regarding [line 421 of index .js ](https://github.com/zpao/qrcode.react/blob/main/src/index.js)

`          preserveAspectRatio="none"` should be  `          preserveAspectRatio="xmidYMid meet" `

which will keep the proportions of the source image without stretching or squishing it

**Comment by zpao** [comment]
That's probably fair, however my intent was that you're not relying on that, and that the code here isn't relying on that. It's incompatible with the `excavate` option ("digging" out space so the image doesn't overlap actual QR Code blocks) - we need to know height and width before we can do that, which is why those are explicit props in `imageSettings`

The SVG component is already much simpler - we don't need to wait for the image to load to do anything, unlike the Canvas renderer, which needs the image to load in order to write it to the canvas. If we change this for SVG, at least when `excavate` is set, we'd need to download the image, determine aspect ratio (or render and read it back, would need to figure it out), then do the excavation based on actual size.

I don't ultimately think it's a bad feature, but it does make things more complicated and can degrade the end user experience. I'm not going to do it but if somebody wants to do it, I'd probably figure out some set of props to indicate preservation of aspect ratio, and potentially maxHeight/Width (instead of height/width). We'd need to do the same for the Canvas component (which is already halfway there since it does work on image load)

**Comment by andyfitz** [comment]
Got you, so consistency between canvas and SVG modes is the main driver for having proportion squishing/stretching the default. 
I've made this change downstream and it suits my needs.

BTW this was super easy to put behind [make.cm](https://make.cm) for a [fancy GET API endpoint](https://cdn.make.cm/make/s/rhsvgqr?data[value]=https://brand.redhat.com&data[level]=M&data[rounded]=true&data[fgColor]=rgb(238,0,0))
I could even add a SVG filter to round the path edges a little. 

Template here https://github.com/RedHatBrand/redhat-qr-code

**Comment by meabed** [comment]
I use the library Thanks zpao! but it's seems unmaintained.

if any interested, I have updated the library and migrate it to typescript https://github.com/devmehq/react-qr-code
if you have any suggestion or improvement and you could open there, i'm happy to help adding more features and improvements to the library! thanks folks.

**Comment by zpao** [comment]
I think I'm going to leave it as is.
