### ISSUE TITLE
Could not find a declaration file

### ISSUE THREAD

**Issue by p-chan** [zpao/qrcode.react#179]
Thanks for releasing v2.0.0!

I found one problem and I am reporting it.
I updated to v2.0.0 and cannot find the type definition.
It seems that the file published to npm does not include the type definition file.
Is it possible to release a version that includes the type definition files?

**Comment by zpao** [comment]
v2 and below do not ship with a `.d.ts` file because they were not written in Typescript. v3 will include one. v2 is virtually identical to v1 though, so if anybody wants to get https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/qrcode.react updated, they are welcome to. I've never maintained that myself and don't intend to start with v3 right around the corner.

**Comment by p-chan** [comment]
I see! Sorry, I was mistaken.
I will meekly wait for v3.
