### ISSUE TITLE
Make QRProps optionals

### ISSUE THREAD

**Issue by Janaka-Steph** [zpao/qrcode.react#197]
TS is complaining that bgColor, fgColor, includeMargin and size are required. They should be optional with default values.

**Comment by zpao** [comment]
What version are you using?

**Comment by Janaka-Steph** [comment]
3.0.2

**Comment by zpao** [comment]
Hmm, it seems to be fine for me. That fits with my knowledge as TS should understand the defaultProps bits in the .d.ts.

Here's a quick test: [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBARQEoGEIBMCmAaOBvZNLFAQwDsA3EgZ10I0wGUA1AcQF84AzKCEOAOQBHKAGMGAOiiYSomAIDcAKFCRYcJDLnde-AdNnzlq6PE2GAIgHkAsjr6CDcgLTo+ipUq4BXMnOAQZHA2AJ4AgmBgABQAlPhKcHDSMN5QQQA8AHwJiXDp9FhwVAA23pgAvABEXBAQlXAA9Nm5eQVMbEUkpRXVtfVNOYn5qAyklDSd3VU1dY3NeU3K7J7mctY2UphkWFBR6aERYHO4bqLeIFswEgDmmDAAosWYF2QwAEIhAJLoUQLiryRgGRMFABDEYgogA)

**Comment by Janaka-Steph** [comment]
I don't understand why it works for you, but it doesn't for me. I checked my TS config, my TS version 4.5.2, but I don't know.
I don't think TS understand defaultProps, it's a React thing, not TS thing. I don't see any `.d.ts` file in the source code.

Anyway it should not break the code to make those props optional, like so:
```
type QRProps = {
  value: string;
  size?: number;
  // Should be a real enum, but doesn't seem to be compatible with real code.
  level: string;
  bgColor?: string;
  fgColor?: string;
  style?: CSSProperties;
  includeMargin?: boolean;
  imageSettings?: {
    src: string;
    height: number;
    width: number;
    excavate: boolean;
    x?: number;
    y?: number;
  };
};
```
What do you think?

**Comment by zpao** [comment]
The `.d.ts` file is generated, you can see the bundled version here: https://unpkg.com/browse/qrcode.react@3.0.2/lib/index.d.ts

defaultProps is a React thing, but TS does have some support for it. They've called out explicit support for it in class components but in my own testing it seems to work identically for function components too.

Here's what those both look like in a `.d.ts`:
```ts
declare type TMyComponentProps = {
    required: string;
    requiredWithDefault: string;
    optional?: string;
};
declare function MyComponent(props: TMyComponentProps): JSX.Element;
declare namespace MyComponent {
    var defaultProps: {
        requiredWithDefault: string;
    };
}
declare class MyComponentClass extends React.Component<TMyComponentProps> {
    render(): JSX.Element;
    static defaultProps: {
        requiredWithDefault: string;
    };
}
```

Now that said, this pattern causes problems once we get beyond the simple use. As I've looked into `forwardProps` - the type inference actually seems to lose the handling. You can set `defaultProps` on a `forwardRef` component _but_ TS doesn't treat that the same way, so it complains about missing props. This is the exact same thing you're seeing so that's enough evidence for me to do exactly as you're asking in terms of making those props optional in the type definition.

https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/default_props/ has some alternatives but they all seem unnecessarily complex for here. Still may be an interesting read.

Note: I think doing this for the direct components would be a safe minor version bump (loosening types, not making them more restrictive) but I'll have to see if it requires anything more drastic.
