### ISSUE TITLE
How do I show the loading status before the QR code comes out？

### ISSUE THREAD

**Issue by qingfengmy** [zpao/qrcode.react#294]
I have two modes, they show different QR codes, when switching, the QR code can not be switched immediately, before the new QR code comes out, I need to show the loading.

**Comment by zpao** [comment]
This is generally a problem with React components. My advice would be to use the mode as a key when rendering, eg `return <QRCodeCanvas key={mode} ... />`. This will force React to throw away the old instance rather than attempt to reuse it. This would be most useful for QRCodeCanvas, which will reuse the actual `<canvas>` DOM node and does that outside of the render cycle.
