### ISSUE TITLE
Support server-side rendering

### ISSUE THREAD

**Issue by MBehtemam** [zpao/qrcode.react#40]
hi i need to create a qr code from my sever, curentlly i user [express-react-view](https://github.com/reactjs/express-react-views) but nothing was render, one thing and it's i have canvas , a canvas that qrcode.react does created but no qr code showed on this canvas

**Comment by zpao** [comment]
`<canvas>` elements need JS to run on the client. The way this React component works is that is uses componentDidMount (and DidUpdate) to to run the imperative canvas APIs after the element exists.

In order to support server rendering we'd need to support another type of rendering, eg using SVG. That is something I've considered but haven't put the time in for, nor have I decided if using SVG is better (has the downside that you can't download directly to png)

So in the meantime, this is expected. Sorry that it doesn't fit your need at the moment.

**Comment by zpao** [comment]
I added support for rendering to SVG in v0.8 so you can use that for server-side rendering.
