### ISSUE TITLE
Incorrect canvas size parameters

### ISSUE THREAD

**Issue by CoonJS** [zpao/qrcode.react#86]
When I rendered my QR code as PNG, I set the size property as 512, but when I'm downloading the PNG image I got a 1024x1024 image.

<img width="1092" alt="Снимок экрана 2019-07-12 в 20 25 10" src="https://user-images.githubusercontent.com/37885113/61146768-7a6ce880-a4e3-11e9-9796-834cbea7c15e.png">

The problem is you use incorrect canvas params when you render a canvas element.

I've got `style="height: 512px; width: 512px;"` but  canvas attributes was`width=1024` and `height=1024`.

How to solve this problem? 
May I do pull request to fix this?
There is any way to solve the problem in the current version?

**Comment by CoonJS** [comment]
I've looked your code and I saw that you multiply `size` prop on the `window.devicePixelRatio`
https://github.com/zpao/qrcode.react/blob/master/src/index.js#L173

But if I use Macbook with retina display I got `window.devicePixelRatio=2`

**Comment by zpao** [comment]
In order to support high density displays (eg Macbook with retina), that size multiplying and setting style is needed. It does have the side effect of making the actual image 2x larger when downloaded. There's no way to really fix that right now :/

FWIW this is the same behavior you get if you just take a screenshot on your computer. The PNG you get out is actually 2x your screen resolution.
