### ISSUE TITLE
About inline styles on canvas

### ISSUE THREAD

**Issue by limin19860601** [zpao/qrcode.react#97]
I don't think the inline styles 'width' and 'height' on canvas is necessary. It's not friendly for users to use their own css.

**Comment by zpao** [comment]
These are necessary in order to create high resolution qrcodes in canvas. We double the actual element height/width based on pixel ratio, draw everything twice as big, and use the inline style to downsize back to the actual `size` specified.

These styles can be overridden if desired. Please read through https://github.com/zpao/qrcode.react#custom-styles
